[package]
name = "cuneus"
version = "0.2.0"
edition = "2021"
authors = ["altunenes"]
description = "A WGPU-based shader development tool"
license = "MIT"
repository = "https://github.com/altunenes/cuneus"
readme = "readme.md"
keywords = ["graphics", "wgpu", "shaders", "gpu"]
categories = ["graphics", "rendering"]

[dependencies]
wgpu = "24.0.1"
winit = "0.30.11"
bytemuck = { version = "1.21", features = ["derive"] }
egui-wgpu = "0.31.1"
egui = "0.31.1"
egui-winit = "0.31.1"
image = { version = "0.25.6", features = ["png", "hdr","exr"] }
env_logger = "0.11.6"
pollster = "0.4.0"
rfd = "0.15.1"
notify = "7.0.0"
gstreamer = "0.23.4"
gstreamer-video = "0.23.4"
gstreamer-app = "0.23.4"
gstreamer-pbutils = "0.23.4"
anyhow = "1.0.96"
log = "0.4.25"
rand = "0.9.1"

[dev-dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
